Repository devdeun/investmetic, pull requests merged in 2024-12, with the labels that each got.

#2 [Feat] 일간 분석 삭제 및 수정 기능
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/my/_api/manage-daily-analysis.ts
  app/(dashboard)/my/_hooks/query/use-get-my-daily-analysis.ts
  app/(dashboard)/my/_hooks/query/use-manage-daily-analysis.ts
  shared/types/strategy-data.ts
  shared/ui/modal/edit-daily-analysis-modal.ts/index.tsx
  shared/ui/modal/edit-daily-analysis-modal.ts/styles.module.scss
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/styles.module.scss
  shared/utils/excel-utils.ts
Labels: ✨ Feature, 📬 API

#4 [Feat] 전략 삭제 모달 및 일간 분석 전체 삭제 모달
  app/(dashboard)/_ui/analysis-container/account-content.tsx
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/my/_api/delete-my-strategy.ts
  app/(dashboard)/my/_hooks/query/use-add-strategy.ts
  app/(dashboard)/my/_hooks/query/use-analysis-mutation.ts
  app/(dashboard)/my/_hooks/query/use-delete-my-strategy.ts
  app/(dashboard)/my/_hooks/query/use-manage-daily-analysis.ts
  app/(dashboard)/my/_hooks/query/use-patch-profile.ts
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(landing)/notices/_ui/notice-detail/index.tsx
  app/admin/notices/post/_api/post-notice.ts
  shared/hooks/custom/use-auth.ts
  shared/hooks/query/auth-queries.ts
  shared/stores/use-auth-store.ts
  shared/ui/button/index.tsx
  shared/ui/header/_ui/header-links/index.tsx
  shared/ui/modal/daily-analysis-delete-all-modal.tsx
  shared/ui/modal/edit-daily-analysis-modal.ts/index.tsx
  shared/ui/modal/strategy-delete-modal.tsx
  shared/ui/table/vertical/index.tsx
  shared/utils/excel-utils.ts
  shared/utils/token-utils.ts
Labels: ✨ Feature, 📬 API

#11 [Refactor] Input 컴포넌트 수정 및 관련 파일 수정
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/page.tsx
  app/(dashboard)/my/strategies/add/page.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
  app/(dashboard)/strategies/_ui/search-bar/index.tsx
  app/(dashboard)/traders/page.tsx
  app/(landing)/signin/page.tsx
  app/(landing)/signup/information/page.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/stock-post-button/index.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/trade-post-button/index.tsx
  app/admin/notices/post/page.tsx
  app/admin/notices/tabledata.tsx
  app/admin/strategies/page.tsx
  app/admin/users/page.tsx
  shared/types/svg.d.ts
  shared/ui/input/index.tsx
  shared/ui/input/input.stories.tsx
  shared/ui/modal/add-question-modal.tsx
  shared/ui/modal/analysis-upload-modal/form/direct-input-form.tsx
  shared/ui/modal/edit-daily-analysis-modal.ts/index.tsx
  shared/ui/modal/find-email-modal/index.tsx
  shared/ui/modal/find-password-modal/index.tsx
  shared/ui/search-input/index.tsx
  shared/ui/search-input/search-input.stories.tsx
  shared/ui/textarea/index.tsx
  shared/ui/textarea/textarea.stories.tsx
Labels: 🔨 Refactor

#12 [ Bug] 공지사항 상세 api 수정
  app/(landing)/notices/_api/get-notice-detail.ts
  app/(landing)/notices/_api/get-notice-file.ts
  app/(landing)/notices/_ui/notice-detail/index.tsx
Labels: 🐛 Bug, 🔨 Refactor

#16 [Bug] 전략랭킹 쿼리키 누락
  app/(dashboard)/strategies/_hooks/query/use-post-strategies.ts
Labels: 🐛 Bug

#19 [Feat] smscore tofixed(1) 처리
  app/(landing)/(home)/_ui/top-strategy-card/index.tsx
Labels: ✨ Feature

#23 [fix] 관리자 카테고리 페이지 종목 비활성화 관련 버그 해결
  app/admin/category/_ui/stock/stock-manage/_hooks/query/use-toggle-stock-active-state.ts
  app/admin/category/_ui/stock/stock-manage/_ui/stock-active-state-toggle-button.tsx
  app/admin/category/_ui/trade/trade-manage/_api/set-admin-trade-manage-table-data.tsx
Labels: 🐛 Bug

#20 [Bug] 로그인이 필요한 페이지에 접근시 로그인 체크 모달이 뜨도록 수정
  app/(dashboard)/_ui/strategies-item/index.tsx
  middleware.ts
  shared/constants/auth.ts
  shared/providers/auth-provider.tsx
  shared/ui/modal/signin-check-modal.tsx
  shared/utils/auth-path.ts
Labels: ✨ Feature

#26 [Refactor] vertical table 컴포넌트에서 비즈니스 로직 분리
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/analysis-container/styles.module.scss
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/styles.module.scss
Labels: 🔨 Refactor

#25 [Feat] useSuspenseQuery 사용을 위한 환경설정
  app/(landing)/notices/_api/get-notice.ts
  app/admin/notices/_hook/query/get-admin-notices.ts
  shared/api/axios.ts
Labels: ✨ Feature

#31 [Feat] 엑셀 업로드 가이드 다운로드 기능 구현
  public/files/엑셀업로드설명.xls
  shared/ui/modal/analysis-upload-modal/form/excel-upload-form.tsx
Labels: ✨ Feature

#37 [Feat] 구독 버튼 누를 때 쿼리키 추가
  app/(dashboard)/strategies/_hooks/query/use-get-subscribe.ts
Labels: ✨ Feature

#41 [Refactor] 문의내역 상세 리팩토링
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/question-detail-card.stories.tsx
  app/(dashboard)/my/questions/_ui/questions-tab-content/index.tsx
  shared/ui/modal/question-delete-modal/index.tsx
  shared/ui/modal/question-delete-modal/styles.module.scss
Labels: 🔨 Refactor

#36 [Feat] 관리자 공지 페이지 - suspense 적용, 삭제 추가
  app/admin/_ui/file-input/index.tsx
  app/admin/notices/_api/delete-notice.ts
  app/admin/notices/_hook/query/use-delete-notice.ts
  app/admin/notices/_ui/admin-notice-table/index.tsx
  app/admin/notices/_ui/admin-notice-table/styles.module.scss
  app/admin/notices/_ui/notice-delete-button/index.tsx
  app/admin/notices/_ui/notice-delete-button/styles.module.scss
  app/admin/notices/page.tsx
  app/admin/notices/post/_api/post-notice.ts
  app/admin/notices/post/_hooks/query/use-post-notice.ts
  app/admin/notices/post/_hooks/use-notice-post.ts
  app/admin/notices/post/page.module.scss
  app/admin/notices/post/page.tsx
  app/admin/notices/post/types.ts
  app/admin/notices/tabledata.tsx
  app/admin/notices/types.ts
Labels: ✨ Feature

#43 [Refactor] 분석컴포넌트 멘토님 코드리뷰 반영
  app/(dashboard)/_ui/analysis-container/account-content.tsx
  app/(dashboard)/_ui/analysis-container/analysis-chart.tsx
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/analysis-container/constants.ts
  app/(dashboard)/_ui/analysis-container/example.ts
  app/(dashboard)/_ui/analysis-container/index.tsx
  app/(dashboard)/_ui/analysis-container/statistics-content.tsx
  app/(dashboard)/my/_api/get-my-account-iamges.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-account-images.ts
  shared/types/strategy-data.ts
Labels: 🔨 Refactor

#46 [Bug] 회원가입 완료 메시지 오류 수정
  app/(landing)/signup/_ui/signup-complete-message/index.tsx
  app/(landing)/signup/_ui/signup-complete-message/styles.module.scss
  app/(landing)/signup/complete/page.tsx
Labels: 🐛 Bug

#51 [Bug] build 에러 해결을 위해 baseUrl 설정
  shared/api/axios.ts
Labels: 🐛 Bug

#47 [Refactor] 전략/ 전략상세 멘토님 코드리뷰 반영
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/strategies-item/area-chart.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/page.tsx
  shared/ui/modal/review-guide-modal.tsx
Labels: 🔨 Refactor

#44 [Feat] 트레이더 API 추가 및 반응형 추가
  app/(dashboard)/traders/[traderId]/page.tsx
  app/(dashboard)/traders/_api/get-trader-details.ts
  app/(dashboard)/traders/_api/get-trader-profile.ts
  app/(dashboard)/traders/_hooks/use-get-trader-profile.ts
  app/(dashboard)/traders/page.module.scss
  shared/ui/header/back-header/index.tsx
  shared/ui/traders-list-card/index.tsx
Labels: ✨ Feature, 📬 API

#55 [Bug] 검색바 에러있을시 데이터 요청가는 에러 해결
  app/(dashboard)/strategies/_hooks/query/use-post-strategies.ts
  app/(dashboard)/strategies/_ui/search-bar/_store/use-searching-item-store.ts
  app/(dashboard)/strategies/_ui/search-bar/accordion-button.tsx
  app/(dashboard)/strategies/_ui/search-bar/accordion-container.tsx
  app/(dashboard)/strategies/_ui/search-bar/index.tsx
  app/(dashboard)/strategies/_ui/search-bar/styles.module.scss
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  app/(dashboard)/strategies/_ui/strategy-list/styles.module.scss
Labels: 🐛 Bug

#54 [Bug] history stack이 쌓여 발생한 뒤로가기 문제 해결
  app/(dashboard)/traders/[traderId]/page.tsx
  shared/hooks/custom/use-pagination.ts
Labels: 🐛 Bug

#48 [Feat] 관리자 질문하기 페이지
  app/admin/questions/_api/delete-admin-question.ts
  app/admin/questions/_api/get-admin-questions.ts
  app/admin/questions/_api/set-admin-question-table-body.tsx
  app/admin/questions/_hooks/query/use-admin-questions.ts
  app/admin/questions/_hooks/query/use-delete-question.ts
  app/admin/questions/_hooks/use-admin-questions-page.ts
  app/admin/questions/_ui/admin-question-delete-button/index.tsx
  app/admin/questions/_ui/admin-question-delete-button/styles.module.scss
  app/admin/questions/_ui/admin-question-state-box/index.tsx
  app/admin/questions/_ui/admin-question-state-box/styles.module.scss
  app/admin/questions/_ui/admin-question-view-detail/index.tsx
  app/admin/questions/_ui/admin-question-view-detail/styles.module.scss
  app/admin/questions/constants.ts
  app/admin/questions/page.module.scss
  app/admin/questions/page.tsx
  app/admin/questions/types.ts
Labels: ✨ Feature

#57 [Bug] 회원가입 관련 쿠키 오류 수정
  app/(landing)/signup/_hooks/custom/use-signup-form.ts
  app/(landing)/signup/_store/use-signup-store.ts
  app/(landing)/signup/_ui/user-type-card/index.tsx
  app/(landing)/signup/complete/page.tsx
Labels: 🐛 Bug

#61 [Feat] OG 이미지 및 description 추가
  app/layout.tsx
  app/opengraph-image.alt.txt
  app/opengraph-image.png
  app/twitter-image.alt.txt
  app/twitter-image.png
Labels: ✨ Feature

#62 [Refactor] 관리자 유저 관리 페이지 코드 리뷰 반영 - 회원 탈퇴시 컨펌창 모달 띄움
  app/admin/users/_api/get-admin-users.ts
  app/admin/users/_api/set-table-body.tsx
  app/admin/users/_ui/user-delete-button.tsx
  app/admin/users/_ui/user-delete-modal/index.tsx
  app/admin/users/page.tsx
Labels: 🔨 Refactor

#64 [Fix] 총별점toFixed 적용
  shared/ui/total-star/index.tsx
Labels: ✨ Feature

#66 [Bug] metadataBase URL 설정
  app/layout.tsx
Labels: 🐛 Bug

#70 [Feat] 프로필 조회, 프로필 수정, 회원 탈퇴 페이지 디자인 수정 및 api 연동
  app/(dashboard)/my/_api/delete-user-withdrawal.ts
  app/(dashboard)/my/_api/patch-user-profile.ts
  app/(dashboard)/my/_api/post-account-image.ts
  app/(dashboard)/my/_hooks/query/use-patch-profile.ts
  app/(dashboard)/my/_hooks/query/use-patch-user-profile.ts
  app/(dashboard)/my/_hooks/query/use-user-withdrawal.ts
  app/(dashboard)/my/profile/_hooks/custom/use-profile-form.ts
  app/(dashboard)/my/profile/_hooks/custom/use-profile-image.ts
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(dashboard)/my/profile/_ui/user-info/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-info/types.ts
  app/(dashboard)/my/profile/_ui/user-profile/index.tsx
  app/(dashboard)/my/profile/_ui/user-profile/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-withdraw/index.tsx
  app/(dashboard)/my/profile/_ui/user-withdraw/styles.module.scss
  app/(dashboard)/my/profile/edit/page.tsx
  app/(dashboard)/my/profile/edit/styles.module.scss
  app/(dashboard)/my/profile/page.tsx
  app/(dashboard)/my/profile/styles.module.scss
  app/(dashboard)/my/profile/withdraw/page.tsx
  app/(dashboard)/my/profile/withdraw/styles.module.scss
  app/(landing)/signup/_constants/signup.ts
  shared/ui/modal/withdraw-check-modal.tsx
Labels: ✨ Feature, 📬 API

#67 [Bug] 전략목록 상태 및 데이터 초기화 적용
  app/(dashboard)/_ui/strategies-item/subscribe.tsx
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  app/(landing)/(home)/_ui/top-strategy-card/index.tsx
  app/(landing)/(home)/_ui/top-strategy-card/styles.module.scss
Labels: 🐛 Bug, 🔨 Refactor

#71 [Design] 일부 디자인 수정 및 나의전략페이지 전략없음UI, 스켈레톤 적용
  app/(dashboard)/my/strategies/_ui/my-strategy-list/index.tsx
  app/(dashboard)/my/strategies/_ui/my-strategy-list/styles.module.scss
  app/(dashboard)/my/strategies/page.tsx
  app/(dashboard)/traders/[traderId]/page.module.scss
  app/(dashboard)/traders/page.module.scss
  app/(landing)/signin/styles.module.scss
Labels: ✨ Feature, 🎨 Design

#74 [Feat] 통계테이블 단위 표시 및 스타일 수정
  shared/ui/table/statistics/constant.ts
  shared/ui/table/statistics/index.tsx
  shared/ui/table/statistics/styles.module.scss
  shared/ui/table/vertical/styles.module.scss
Labels: ✨ Feature

#77 [Design] 문의 내역 empty message 스타일 수정
  app/(dashboard)/my/questions/_ui/questions-tab-content/styles.module.scss
Labels: 🎨 Design

#78 [Bug] 일반유저에게 삭제버튼 보이지 않도록 처리
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
Labels: 🐛 Bug

#80 [Feat] 슈퍼 어드민 계정일때 사이드바에 나의 전략 탭 추가
  app/(dashboard)/_ui/navigation.tsx
  shared/types/auth.ts
  shared/ui/side-navigation/styles.module.scss
Labels: ✨ Feature

#86 [Bug] 관리자 카테고리 페이지 활성화 버튼 버그
  app/admin/category/_ui/shared/manage-table/index.tsx
  app/admin/category/_ui/shared/manage-table/utils/add-index-to-data.tsx
  app/admin/category/_ui/stock/stock-manage/_api/set-admin-stock-manage-table-data.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/active-stock-manage-table.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/inactive-stock-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_api/get-trades.ts
  app/admin/category/_ui/trade/trade-manage/_api/set-admin-trade-manage-table-data.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/active-trade-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/inactive-trade-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/trade-active-state-toggle-button.tsx
Labels: 🐛 Bug

#82 [Bug] 전략이 없어도 트레이더 상세 페이지가 뜨도록 수정
  app/(dashboard)/traders/[traderId]/page.module.scss
  app/(dashboard)/traders/[traderId]/page.tsx
Labels: 🐛 Bug

#92 [Bug] 관리자 회원 관리 페이지네이션
  app/admin/users/_api/set-table-body.tsx
  app/admin/users/_hooks/use-user-search-page.ts
  app/admin/users/page.tsx
Labels: 🐛 Bug

#89 [Bug] 파일 다운로드시 파일명, 확장자명 오류 해결
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis-download.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-proposal-download.ts
  app/(dashboard)/strategies/[strategyId]/_api/helper-download-file.ts
Labels: 🐛 Bug

#98 [Bug] 관리자 세션 모달 뜨지 않는 문제 해결
  next.config.mjs
  shared/api/axios.ts
  shared/constants/auth.ts
  shared/hooks/custom/use-auth.ts
  shared/hooks/custom/use-session-expiry-warning.tsx
  shared/providers/auth-provider.tsx
  shared/ui/modal/index.tsx
Labels: 🐛 Bug

#101 [Bug] 로그인 박스가 로그인 페이지 중앙에 고정되도록 변경
  app/(landing)/signin/styles.module.scss
  shared/ui/header/logo-header/index.tsx
Labels: 🐛 Bug

#104 [Fix] useSuspenseQuery -> useQuery로 변경
  app/admin/notices/_hook/query/get-admin-notices.ts
  app/admin/notices/_ui/admin-notice-table/index.tsx
Labels: 🔨 Refactor

#102 [Fix] 네비게이션바 유저프로필 avatar컴포넌트 적용
  shared/ui/avatar/index.tsx
  shared/ui/side-navigation/nav-link-item.tsx
  shared/ui/side-navigation/styles.module.scss
  shared/ui/side-navigation/user-navigation.tsx
Labels: ✨ Feature

#109 [Fix] 종목 및 매매유형 추가 presignedUrl 처리방식 변경
  app/admin/category/_ui/shared/_api/upload-file-with-presigned-url.ts
Labels: 🐛 Bug

#106 [Feat] alert modal 공통 컴포넌트 작업 및 관리자 페이지에 적용
  app/admin/notices/_ui/admin-notice-table/index.tsx
  app/admin/notices/_ui/notice-delete-button/index.tsx
  app/admin/questions/_ui/admin-question-delete-button/index.tsx
  app/admin/users/_api/set-table-body.tsx
  app/admin/users/_ui/user-delete-button.tsx
  app/admin/users/page.tsx
  shared/ui/modal/alert-modal/index.tsx
Labels: ✨ Feature

#111 [Refactor] 로그아웃 시 검색 상태도 초기화되도록 수정 및 엑셀 업로드 오류메시지 세분화
  shared/hooks/query/auth-queries.ts
  shared/utils/excel-utils.ts
Labels: 🔨 Refactor

#112 [Feat] 전략 수정
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/details-information/invest-information.tsx
  app/(dashboard)/_ui/details-information/strategy-name-box.tsx
  app/(dashboard)/_ui/details-information/styles.module.scss
  app/(dashboard)/_ui/details-side-item/index.tsx
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/_ui/details-side-item/styles.module.scss
  app/(dashboard)/_ui/introduction/index.tsx
  app/(dashboard)/_ui/subscriber-item/index.tsx
  app/(dashboard)/_ui/subscriber-item/styles.module.scss
  app/(dashboard)/my/_api/post-edit-strategy.ts
  app/(dashboard)/my/_hooks/query/use-post-edit-strategy.ts
  app/(dashboard)/my/strategies/manage/[strategyId]/_store/use-edit-information-store.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
Labels: ✨ Feature

#115 [Feat] 관리자 전략 관리 페이지 - 수정 삭제 버튼 추가
  app/(dashboard)/my/_api/delete-my-strategy.ts
  app/admin/strategies/_api/set-admin-strategies-table-body.tsx
  app/admin/strategies/_hooks/query/use-admin-delete-strategy.ts
  app/admin/strategies/_hooks/use-admin-strategies-page.ts
  app/admin/strategies/_ui/button/strategy-delete-button copy.tsx
  app/admin/strategies/_ui/button/strategy-edit-button.tsx
  app/admin/strategies/_ui/button/styles.module.scss
  app/admin/strategies/page.tsx
Labels: ✨ Feature

#122 [Bug] 추가 문의 등록 후 문의내역 페이지 업데이트가 되지 않음
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-post-question.ts
Labels: 🐛 Bug

#120 [Fix] 관리자 공지 페이지 - 파일 등록 기능 개선
  app/admin/notices/_hook/use-admin-notice-page.ts
  app/admin/notices/_ui/admin-notice-table/index.tsx
  app/admin/notices/_ui/button/notice-delete-button.tsx
  app/admin/notices/_ui/button/notice-edit-button.tsx
  app/admin/notices/_ui/button/styles.module.scss
  app/admin/notices/post/_hooks/query/use-post-notice.ts
  app/admin/notices/post/page.tsx
Labels: 🐛 Bug

#119 [Bug] 트레이더 상세 backheader에 트레이더 목록으로 가는 href 추가
  app/(dashboard)/traders/[traderId]/page.tsx
Labels: 🐛 Bug

#127 [Fix] 로그인 페이지에서 로그인 체크 모달이 뜨지 않도록 수정
  shared/providers/auth-provider.tsx
Labels: 🐛 Bug

#132 [Feat] 문의내역 유저 타입에 따른 프로필 이미지 및 닉네임 출력
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/_ui/questions-tab-content/index.tsx
  shared/types/questions.ts
Labels: ✨ Feature

#133 [Fix] 관리자 전략 관리 페이지 - 테이블 이상 해결
  app/admin/strategies/_hooks/use-admin-strategies-page.ts
  app/admin/strategies/page.tsx
Labels: 🐛 Bug

#139 [Fix] textarea 엔터키 적용되도록 수정
  app/(dashboard)/_ui/introduction/index.tsx
  app/(dashboard)/_ui/introduction/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
  app/(landing)/notices/_ui/notice-detail/index.tsx
  app/(landing)/notices/_ui/notice-detail/styles.module.scss
  app/admin/notices/post/page.module.scss
  app/admin/notices/post/page.tsx
Labels: ✨ Feature

#141 [Fix] isBrowser 변수를 함수로 변경
  app/(landing)/signup/_lib/cookies.ts
Labels: 🐛 Bug

#142 [Docs] README.md 작성
  README.md
Labels: 📃 Docs

#144 [Feat] Footer 정보 수정
  shared/ui/footer/index.tsx
  shared/ui/footer/styles.module.scss
Labels: ✨ Feature
