Repository devdeun/investmetic, pull requests merged in 2025-01, with the labels that each got.

#146 [Feat] 관리자 페이지 공지사항 등록 및 수정 첨부파일 목록 출력
  app/admin/notices/[noticeId]/edit/_hooks/query/use-patch-notice.ts
  app/admin/notices/[noticeId]/edit/page.module.scss
  app/admin/notices/[noticeId]/edit/page.tsx
  app/admin/notices/[noticeId]/edit/types.ts
  app/admin/notices/_hook/use-file-handler.ts
  app/admin/notices/_ui/notice-file-item/index.tsx
  app/admin/notices/_ui/notice-file-item/styles.module.scss
  app/admin/notices/post/_hooks/query/use-post-notice.ts
  app/admin/notices/post/_hooks/use-notice-form.ts
  app/admin/notices/post/page.module.scss
  app/admin/notices/post/page.tsx
  app/admin/notices/types.ts
  shared/ui/modal/notification-modal/index.tsx
Labels: ✨ Feature

#147 [Feat] 전략 제안서 관련 수정
  app/(dashboard)/my/strategies/add/page.tsx
  app/(dashboard)/my/strategies/add/styles.module.scss
  shared/ui/error-message/styles.module.scss
Labels: ✨ Feature, 🔨 Refactor

#149 [Bug] 관리자가 리뷰를 삭제할 수 있도록 onClick 이벤트 핸들러 추가
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
Labels: 🐛 Bug

#154 [Feat] 엑셀 업로드 모달 안내문구 추가 및 일간 분석 테이블 스켈레톤 적용
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  shared/hooks/custom/use-delayed-loading.ts
  shared/ui/modal/analysis-upload-modal/form/direct-input-form.tsx
  shared/ui/modal/analysis-upload-modal/form/excel-upload-form.tsx
  shared/ui/modal/analysis-upload-modal/form/styles.module.scss
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/styles.module.scss
Labels: ✨ Feature, 🔨 Refactor

#155 Feat] 관리자 페이지 매매유형 삭제 기능 추가
  app/admin/category/_ui/trade/trade-manage/_api/delete-inactive-trade.ts
  app/admin/category/_ui/trade/trade-manage/_api/set-admin-trade-manage-table-data.tsx
  app/admin/category/_ui/trade/trade-manage/_hooks/query/use-delete-inactive-trade.ts
  app/admin/category/_ui/trade/trade-manage/_ui/inactive-trade-delete-button.tsx
  app/admin/category/_ui/trade/trade-manage/types.ts
  shared/ui/table/vertical/styles.module.scss
Labels: ✨ Feature

#157 [Bug] 테이블 셀렉트 오류 해결
  app/admin/users/_ui/role-select.tsx
  app/admin/users/constants.ts
  shared/ui/table/vertical/styles.module.scss
Labels: 🐛 Bug

#158 [Feat] 전략 수정페이지에서 제안서 업로드 가능하도록 기능 추가
  app/(dashboard)/_ui/details-information/strategy-name-box.tsx
  app/(dashboard)/_ui/details-information/styles.module.scss
  app/(dashboard)/my/_api/add-strategy.ts
  app/(dashboard)/my/_api/get-proposal-file-name.ts
  app/(dashboard)/my/_api/post-edit-strategy.ts
  app/(dashboard)/my/_hooks/query/use-add-strategy.ts
  app/(dashboard)/my/_hooks/query/use-get-proposal-file-name.ts
  app/(dashboard)/my/_hooks/query/use-post-edit-strategy.ts
  app/(dashboard)/my/strategies/add/page.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/_store/use-edit-information-store.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-proposal-download.ts
  app/admin/category/_ui/shared/_hooks/use-category-icon-post.ts
  app/admin/category/_ui/stock/stock-manage/types.ts
  app/admin/notices/[noticeId]/edit/_hooks/query/use-patch-notice.ts
  shared/api/upload-file-with-presigned-url.ts
  shared/constants/query-key.ts
  shared/constants/supported-file-types.ts
  shared/hooks/custom/use-delayed-loading.ts
  shared/utils/upload-files-with-presigned-url.ts
Labels: ✨ Feature, 🐛 Bug, 🔨 Refactor
