Repository devdeun/investmetic, pull requests merged in 2025-02, with the labels that each got.

#164 [Refactor] 주석 제거, 불필요한 코드 제거 및 기타 리팩토링
  app/(dashboard)/my/strategies/add/page.tsx
  app/admin/_ui/file-input/index.tsx
  app/admin/category/_ui/shared/manage-table/index.tsx
  app/admin/category/_ui/shared/manage-table/styles.module.scss
  app/admin/category/_ui/stock/stock-manage/_api/delete-inactive-stock.ts
  app/admin/category/_ui/stock/stock-manage/_api/get-stocks.ts
  app/admin/category/_ui/stock/stock-manage/_api/toggle-stock-active-state.ts
  app/admin/category/_ui/stock/stock-manage/_ui/stock-post-button/styles.module.scss
  app/admin/category/_ui/trade/trade-manage/_api/get-trades.ts
  app/admin/category/_ui/trade/trade-manage/_api/toggle-trade-active-state.ts
  app/admin/category/_ui/trade/trade-manage/_ui/trade-post-button/styles.module.scss
  app/admin/notices/_ui/admin-notice-table/styles.module.scss
  app/admin/notices/page.module.scss
  app/admin/questions/_ui/admin-question-view-detail/index.tsx
  app/admin/questions/_ui/admin-question-view-detail/styles.module.scss
  app/admin/strategies/_api/get-strategies.ts
  app/admin/strategies/_api/patch-strategy-approval.ts
  app/admin/strategies/_ui/admin-strategy-public-select.tsx
  shared/hooks/query/auth-queries.ts
Labels: 🔨 Refactor

#168 docs: README 내용 수정 (#165)
  README.md
Labels: 📃 Docs

#169 [Feat] 가입일자 확인 가능하도록 마이페이지 및 회원관리 페이지 수정
  app/(dashboard)/my/_api/get-profile.ts
  app/(dashboard)/my/profile/_hooks/custom/use-profile-form.ts
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(dashboard)/my/profile/_ui/user-info/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-info/types.ts
  app/admin/users/_api/set-table-body.tsx
  app/admin/users/page.tsx
  app/admin/users/types.ts
  shared/ui/side-navigation/styles.module.scss
Labels: ✨ Feature

#170 [Feat] 일간분석 및 월간분석 백분율 적용
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/strategies/[strategyId]/util.ts
  shared/types/strategy-data.ts
  shared/ui/table/statistics/constant.ts
  shared/ui/table/statistics/index.tsx
Labels: ✨ Feature

#172 [Fix] 메인 페이지 그래프 유틸 함수 추가 및 로딩 스피너 개선
  app/(landing)/(home)/_ui/average-metrics-section/average-metrics-chart.tsx
  app/(landing)/(home)/_ui/average-metrics-section/index.tsx
  app/(landing)/(home)/_ui/top-favorite-section/index.tsx
  app/(landing)/(home)/_ui/top-sm-score-section/index.tsx
  app/(landing)/(home)/_ui/user-metrics-section/index.tsx
  app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
  shared/utils/chart.ts
Labels: 🐛 Bug, 🔨 Refactor

#174 [Bug] 로그인 에러처리 관련 버그 수정
  app/(dashboard)/_ui/details-information/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-info/styles.module.scss
  app/(dashboard)/traders/page.module.scss
  app/(landing)/signin/page.tsx
  shared/constants/error-messages.ts
  shared/ui/modal/account-register-modal/styles.module.scss
  shared/ui/modal/analysis-upload-modal/form/styles.module.scss
  shared/ui/modal/edit-daily-analysis-modal.ts/styles.module.scss
Labels: 🐛 Bug, 🎨 Design

#179 [Fix] 분석 차트에서 전체 범위의 데이터를 표시하도록 수정
  app/(dashboard)/_ui/analysis-container/analysis-chart.tsx
Labels: ✨ Feature, 🐛 Bug

#180 [Feat] admin 문의 내역 페이지 페이지네이션 handler 함수 추가
  app/admin/questions/page.tsx
Labels: ✨ Feature, 🐛 Bug

#181 [Feat] 제안서 삭제 기능 추가
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/details-information/strategy-name-box.tsx
  app/(dashboard)/_ui/details-information/styles.module.scss
  app/(dashboard)/my/_api/post-edit-strategy.ts
  app/(dashboard)/my/_hooks/query/use-post-edit-strategy.ts
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  public/icons/index.tsx
  public/icons/trashcan.svg
Labels: ✨ Feature

#182 [Bug] 서치바 검색 인풋 초기화 버그 해결
  app/(dashboard)/strategies/_ui/search-bar/range-container.tsx
Labels: 🐛 Bug

#184 [Feat] 랜딩 페이지 전략 카드에 상세 페이지 연결
  app/(landing)/(home)/_ui/top-favorite-section/index.tsx
  app/(landing)/(home)/_ui/top-sm-score-section/index.tsx
  app/(landing)/(home)/_ui/top-strategy-card/index.tsx
  app/(landing)/(home)/_ui/top-strategy-card/top-favorite-card.tsx
  app/(landing)/(home)/_ui/top-strategy-card/top-sm-score-card.tsx
  app/(landing)/(home)/_ui/top-strategy-card/types.ts
Labels: ✨ Feature
